version: '2'
services:
  redis:
    image: redis:3.2
    container_name: botkit-redis
    ports:
      - '6379'
    volumes:
      - ./redis:/data
    command: redis-server --appendonly yes
  elichica:
    build: .
    image: elichica-botkit
    container_name: elichica-botkit
    environment:
      REDIS_URL: redis://redis:6379
      WEB_SERVER_PORT: '8080'
      GOOGLE_CLIENT_SECRET_PATH: token/google-calendar.json
      DEBUG_INFO_CHANNEL: bot-test
    links:
      - redis
    ports:
      - '8080:8080'
